### ISSUE TITLE
You might be the one we're looking for.

### ISSUE THREAD

**Issue by amriogit** [grammy-jiang/s-douban#1]
Hello, our company is looking for engineers in the direction of crawler. It seems that you are very attractive to us, so we would like to know more about it. This is my email amriogm@gmail.com. I hope you can contact us. Thank you.

**Comment by grammy-jiang** [comment]
Hi, @amriogit 

Thanks for you message. Would you introduce more about you?

**Comment by amriogit** [comment]
Glad to see your reply! We are an established credit bureaus "[鹏元征信有限公司](https://www.pycredit.cn/)", focus on personal credit reports, credit reports, below is our recruitment information, if you are interested in can find their contact information in the article, thank you again for your reply.

[http://mp.weixin.qq.com/s/d_Y7l5Ax1Ke2gZPv4R9SCQ](http://mp.weixin.qq.com/s/d_Y7l5Ax1Ke2gZPv4R9SCQ)

**Comment by amriogit** [comment]
We look forward to further discussion! If possible, we would like to have your contact information, or you can contact us, phone number 18923827205, miss zhu.

**Comment by grammy-jiang** [comment]
@amriogit , sure.
